"""Initial migration

Revision ID: 883c1bbd2d0b
Revises: 
Create Date: 2024-06-08 22:23:19.233955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883c1bbd2d0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('game_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('game_type_id', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_file')
    op.drop_table('rule')
    op.drop_table('game_type')
    # ### end Alembic commands ###
